default_context:
  project_name: 'lobbyradar'
  project_slug: 'lobbyradar'
  domain_main: 'lobbyradar.io'
  domain_staging: 'stag.lobbyradar.io'
  docker_swarm_stack_name_main: 'lobbyradar-io'
  docker_swarm_stack_name_staging: 'stag-lobbyradar-io'
  secret_key: 'changethis'
  first_superuser: 'admin@lobbyradar.io'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:5173", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.lobbyradar.io", "https://stag.lobbyradar.io", "https://lobbyradar.io"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@lobbyradar.io'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@lobbyradar.io'
  pgadmin_default_user_password: 'changethis'
  traefik_constraint_tag: 'lobbyradar.io'
  traefik_constraint_tag_staging: 'stag.lobbyradar.io'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
